# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
 # Test against these versions of Node.js
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  - npm install --python="C:\Python27"  # "C:\Python27-x64"

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
